# Default values for Rails
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: web
  type: ClusterIP
  externalPort: 8000
  internalPort: 8080
ingress:
  enabled: false